### ISSUE TITLE
I want to know the version of PyTorch-Geometric  installed, I did not find PyTorch-Geometric 1.10.*

### ISSUE THREAD

**Issue by philtruing** [will-leeson/graves#4]

**Comment by will-leeson** [comment]
It appears tags past 1.7 are not on their github repo. I believe the things I use are backwards compatible. So, you should be able to use the latest version. I will double check

**Comment by philtruing** [comment]
thanks for your reply，but i meet a new problem
when i run 

`python3 src/networks/netTrainer.py data/subsetTrainFiles.json data/subsetValFiles.json data/subsetTestFiles.json data/final_graphs --mp-layers 1 --epochs 2`

an error has occurred:
Traceback (most recent call last):                                                                                                                          
  File "src/networks/netTrainer.py", line 85, in <module>
    np.savez_compressed(returnString+".npz", train_acc = train_acc, train_loss = train_loss, val_acc = val_acc, val_loss = val_loss, overallRes=overallRes, overflowRes=overflowRes, reachSafetyRes=reachSafetyRes, terminationRes=terminationRes, memSafetyRes=memSafetyRes, overallChoices=overallChoices, overflowChoices=overflowChoices, reachSafetyChoices=reachSafetyChoices, terminationChoices=terminationChoices, memSafetyChoices=memSafetyChoices)
  File "<__array_function__ internals>", line 5, in savez_compressed
  File "/root/miniconda3/lib/python3.8/site-packages/numpy/lib/npyio.py", line 689, in savez_compressed
    _savez(file, args, kwds, True)
  File "/root/miniconda3/lib/python3.8/site-packages/numpy/lib/npyio.py", line 715, in _savez
    zipf = zipfile_factory(file, mode="w", compression=compression)
  File "/root/miniconda3/lib/python3.8/site-packages/numpy/lib/npyio.py", line 112, in zipfile_factory
    return zipfile.ZipFile(file, *args, **kwargs)
  File "/root/miniconda3/lib/python3.8/zipfile.py", line 1251, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: 'alg=False_cache=False_dataset=[data/final_graphs]_edge_sets=[AST_Data_ICFG]_epochs=2_gpu=0_mode=cat_mp_layers=1_net=GAT_no_jump=True_pool_type=mean_problem_types=[termination_overflow_reachSafety_memSafety]_task=rank_test=[data/subsetTestFiles.json]_topk=3_train=[data/subsetTrainFiles.json]_val=[data/subsetValFiles.json]_1683946558.npz'

**Comment by will-leeson** [comment]
Ahh, sorry. This is a "it works on my machine" kind of issue. Instead of coming up with some fancy way to name the output files (training weights and statistics files), I just dumped the argparse values to a string. It looks like the "data/..." strings break it. I'll push a fix

**Comment by will-leeson** [comment]
Are you using the tagged version of the repo? It looks like this should be fixed on the main branch
